import {Component, lazy, Suspense, useEffect, useState, type FormEvent, type ReactNode} from 'react'
import {ArrowUpRight, ArrowRight, Search, ShieldCheck, BookOpen, History, Settings2, Database, Check, Download, LogOut, Play, Pause, Menu, X, RefreshCw, ChevronRight} from 'lucide-react'
import {request, setCsrf, date, safeLink, type Profile, type Investigation, type Overview, type LibraryRecord, type Settings, type TeamUser, type Sources, type AuditEvent} from './api'
const Scene=lazy(()=>import('./Scene'))
class GraphicsBoundary extends Component<{children:ReactNode},{failed:boolean}> {
  state={failed:false}; static getDerivedStateFromError(){return {failed:true}}
  render(){return this.state.failed ? <div className="scene-fallback"><img src="/mark.svg" alt="ThreatLeans monogram"/><p>Evidence. In focus.</p></div> : this.props.children}
}
function useData<T>(path:string) {
  const [data,setData]=useState<T|null>(null),[error,setError]=useState(''),[version,setVersion]=useState(0)
  useEffect(()=>{let active=true; setError(''); setData(null); request<T>(path).then(d=>{if(active)setData(d)}).catch(e=>{if(active)setError(e.message)}); return()=>{active=false}},[path,version])
  return {data,error,reload:()=>setVersion(v=>v+1)}
}
function Status({value}:{value:string}) {return <span className={'status '+ (value==='supported'||value==='approved'||value==='complete' ? 'good':'')}><span/>{value.replaceAll('_',' ')}</span>}
function SourceLink({url,children}:{url:string;children:ReactNode}) {const safe=safeLink(url);return safe ? <a href={safe} target="_blank" rel="noopener noreferrer">{children}<ArrowUpRight size={14}/></a> : <span>{children}</span>}

function Landing({onEnter}:{onEnter:()=>void}) {
  const [motion,setMotion]=useState(!window.matchMedia('(prefers-reduced-motion: reduce)').matches)
  const [selected,setSelected]=useState(0)
  const examples=['vulnerability','technique','group']
  const demo=useData<Investigation['result']>('/public/demo?example='+examples[selected])
  return <div className="landing">
    <header className="public-nav"><a href="#" className="wordmark"><img src="/mark.svg" alt=""/>ThreatLeans</a><nav aria-label="Main"><a href="#how">How it works</a><a href="#evidence">Explore the evidence</a></nav><button onClick={onEnter}>Open workspace <ArrowUpRight size={16}/></button></header>
    <main>
      <section className="hero">
        <div className="hero-copy"><h1>Intelligence.<br/>With evidence<br/>at its core.</h1><p>From scattered security sources to a decision you can defend. Trace every finding back to the record.</p><button className="primary" onClick={onEnter}>Enter your workspace <ArrowRight size={19}/></button><a className="text-link" href="#evidence">See a real investigation <ChevronRight size={16}/></a><div className="hero-note"><ShieldCheck size={17}/><span>Self-hosted. Evidence-first. No AI subscription required.</span></div></div>
        <div className="hero-visual"><GraphicsBoundary><Suspense fallback={<div className="scene-loading">Bringing evidence into focus…</div>}><Scene motion={motion} selected={selected}/></Suspense></GraphicsBoundary><div className="scene-caption"><span>One question. Multiple perspectives.</span><button onClick={()=>setMotion(v=>!v)} aria-label={motion?'Pause animation':'Play animation'}>{motion?<Pause size={15}/>:<Play size={15}/>}</button></div><div className="source-switch" aria-label="Select an evidence example">{['Vulnerability','Technique','Threat group'].map((label,i)=><button key={label} className={selected===i?'active':''} onClick={()=>setSelected(i)} aria-pressed={selected===i}>{label}</button>)}</div></div>
      </section>
      <div className="source-strip"><span>Built on the original record</span><span>CISA KEV</span><span>NVD / CVE Program</span><span>MITRE ATT&CK</span><span>OWASP</span></div>
      <section id="evidence" className="public-evidence"><div className="section-intro"><h2>The source is<br/>part of the answer.</h2><p>This is a live example from this deployment’s indexed public records. Each finding keeps its source, observation time, and verification trail.</p></div><div className="live-case"><div className="case-heading"><h3>{selected===0?'CVE-2021-44228':selected===1?'T1566 · Phishing':'G0016 · APT29'}</h3>{demo.data&&<Status value={demo.data.status}/>}</div>{demo.error?<p className="error">Evidence could not load. {demo.error}</p>:!demo.data?<p role="status">Loading recorded evidence…</p>:<><div className="sample-claims">{demo.data.claims.slice(0,3).map((c,i)=><p key={i}>{c.text}<span className="citation">{c.evidence.join(' / ')}</span></p>)}</div><div className="sample-source">{demo.data.evidence.slice(0,3).map(e=><div key={e.id}><SourceLink url={e.url}>{e.source}</SourceLink><small>Observed {date(e.fetched_at)}</small></div>)}</div><small>Recorded source fields · {demo.data.retrieval_mode} retrieval. A source record does not establish your exposure or attribution.</small></>}</div></section>
      <section id="how" className="method"><h2>Ask. Inspect.<br/>Make the call.</h2><div className="method-list"><article><span>Ask a precise question</span><p>Look up a CVE, explore an ATT&CK technique, or search for related public evidence.</p></article><article><span>Follow the record</span><p>Compare source-specific scores, inspect original excerpts, and see what was actually checked.</p></article><article><span>Keep uncertainty visible</span><p>Missing facts and conflicting records go to analyst review. Optional AI interpretation stays separate.</p></article></div></section>
      <section className="closing"><h2>Your next decision<br/>deserves a source.</h2><button className="primary" onClick={onEnter}>Open ThreatLeans <ArrowUpRight size={20}/></button></section>
    </main><footer className="public-footer"><span className="wordmark">ThreatLeans</span><span>A shared workspace for security intelligence.</span><a href="/vendor/NOTICES.txt">Graphics notices</a></footer>
  </div>
}

function SignIn({onLogin,onBack}:{onLogin:(p:Profile)=>void;onBack:()=>void}) {
  const [username,setUsername]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const p=await request<Profile>('/auth/login',{username,password});setCsrf(p.csrf);onLogin(p)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <main className="signin"><button className="text-link" onClick={onBack}>← Back to ThreatLeans</button><div className="signin-layout"><div><span className="wordmark">ThreatLeans</span><h1>Bring the evidence.<br/>Make the decision.</h1><p>Your team’s sources, investigations and review trail. In one workspace.</p></div><form onSubmit={submit}><h2>Sign in to your SOC</h2><p>Use the account created by your administrator.</p><label>Username<input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} required maxLength={80}/></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy?'Signing in…':'Enter workspace'}<ArrowRight size={17}/></button><small>Ask your SOC administrator for an account.</small></form></div></main>
}

function ResultView({inv,onReview}:{inv:Investigation;onReview?:()=>void}) {
  const [selected,setSelected]=useState(0)
  useEffect(()=>setSelected(0),[inv.id])
  const result=inv.result
  if(!result?.evidence)return <p className="error">This investigation did not complete. Retry the question or ask a reviewer.</p>
  const source=result.evidence[selected]
  return <div className="result-layout"><section className="answer-pane"><div className="case-heading"><h2>{inv.question}</h2><Status value={result.status}/></div><div className="answer-meta">{result.verification_mode} · {result.retrieval_mode} · {result.elapsed_ms} ms</div>{result.warnings.map((w,i)=><p className="notice" key={i}>{w}</p>)}{result.claims.length ? result.claims.map((c,i)=><p className="claim" key={i}>{c.text} {c.evidence.map(ref=><button className="citation" key={ref} onClick={()=>setSelected(Number(ref.slice(1))-1)} aria-label={'Inspect source '+ref}>{ref}</button>)}{c.corroborated_by?.length>0&&<small>Corroborated in {c.corroborated_by.join(', ')}</small>}</p>):<p>{result.answer}</p>}
    {result.ai&&<div className="ai-interpretation"><h3>Optional AI interpretation</h3><small>{result.ai.verification} · {result.ai.provider} / {result.ai.model}</small><p>{result.ai.text}</p><details><summary>Provider attempts</summary>{result.ai.attempts.map((a,i)=><p key={i}>{a.provider} — {a.status} · {a.elapsed_ms} ms {a.reason}</p>)}</details></div>}
    <details className="verification"><summary>Claim verification · {result.claims.length} recorded checks</summary><div className="table-scroll"><table><thead><tr><th>Field</th><th>Source</th><th>Result</th></tr></thead><tbody>{result.claims.map((c,i)=><tr key={i}><td>{c.field.replaceAll('_',' ')}</td><td>{c.evidence.join(', ')}</td><td>{c.status}</td></tr>)}</tbody></table></div></details>
    <details><summary>Workflow and limitations</summary>{result.trace.map((t,i)=><p key={i}><strong>{t.role}</strong> · {t.detail}</p>)}{result.limitations.map(l=><p key={l}>{l}</p>)}<small>Corpus generation {result.corpus_generation}</small></details><div className="case-actions"><a className="button" href={'/api/investigations/'+inv.id+'/export'}><Download size={16}/>Export case</a>{onReview&&<button onClick={onReview}>Request review <ArrowUpRight size={16}/></button>}</div>
  </section><aside className="evidence-pane"><h3>Evidence ledger <span>{result.evidence.length}</span></h3><div className="source-tabs">{result.evidence.map((e,i)=><button key={e.id} onClick={()=>setSelected(i)} className={selected===i?'active':''} aria-pressed={selected===i}>E{i+1} <span>{e.source}</span></button>)}</div>{source?<><h4>{source.title}</h4><SourceLink url={source.url}>Inspect original source</SourceLink><small>Observed {date(source.fetched_at)}</small><blockquote>{source.excerpt}</blockquote><details open><summary>Recorded fields</summary><pre>{JSON.stringify(source.facts,null,2)}</pre></details><details><summary>Provenance</summary><code>{source.sha256}</code><p>Match: {source.match}. Rank score is a retrieval score, not a probability of truth.</p></details></>:<p>No matching evidence. Missing information stays unknown.</p>}</aside></div>
}

function Workspace({overview,openInv}:{overview:Overview|null;openInv?:Investigation|null}) {
  const [question,setQuestion]=useState(''),[provider,setProvider]=useState('evidence'),[online,setOnline]=useState(false),[share,setShare]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[inv,setInv]=useState<Investigation|null>(openInv||null),[notice,setNotice]=useState('')
  useEffect(()=>{if(openInv){setInv(openInv);setQuestion(openInv.question)}},[openInv])
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');setNotice('');try{setInv(await request<Investigation>('/investigate',{question,provider,online,share_external:share}))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function review(){if(!inv)return;try{await request('/investigations/'+inv.id+'/review',{status:'pending',note:''});setNotice('Sent to your team’s review queue.')}catch(e){setError((e as Error).message)}}
  return <><div className="page-heading"><div><h1>Investigation workspace</h1><p>Ask a question. Follow the evidence.</p></div><span className="quiet-tag">{overview?.retrieval_mode||'Checking'} search</span></div><form className="question-form" onSubmit={submit}><label htmlFor="question">Your question</label><textarea id="question" value={question} onChange={e=>setQuestion(e.target.value)} placeholder="What is known about CVE-2021-44228?" required minLength={3} maxLength={2000}/><div className="query-controls"><label className="select-label">Answer mode<select value={provider} onChange={e=>{setProvider(e.target.value);setShare(false)}}><option value="evidence">Evidence only · free</option>{overview?.providers.filter(p=>p.configured).map(p=><option key={p.id} value={p.id}>{p.id} · {p.model}</option>)}</select></label><label className="check-label"><input type="checkbox" checked={online} onChange={e=>setOnline(e.target.checked)}/>Live NVD / CVE check</label><button className="primary" disabled={busy||(['openai','anthropic'].includes(provider)&&!share)}>{busy?'Investigating…':'Investigate'}<ArrowRight size={17}/></button></div>{['openai','anthropic'].includes(provider)&&<label className="check-label consent"><input type="checkbox" checked={share} onChange={e=>setShare(e.target.checked)}/>Share this question and public evidence with the configured external AI providers, including permitted fallback providers.</label>}</form>{!inv&&!busy&&<div className="example-questions">Try a recorded entity: {['CVE-2021-44228','T1566','G0016'].map(q=><button key={q} onClick={()=>setQuestion(q)}>{q}<ArrowUpRight size={13}/></button>)}</div>}{busy&&<p role="status" className="notice">Searching recorded sources and checking cited fields. Optional live checks can take up to a minute.</p>}{error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}{inv&&<ResultView inv={inv} onReview={review}/>}</>
}

function Library() {
  const [query,setQuery]=useState(''),[term,setTerm]=useState(''),[kind,setKind]=useState(''),[page,setPage]=useState(1),[selected,setSelected]=useState<LibraryRecord|null>(null)
  const r=useData<{items:LibraryRecord[];total:number}>('/library?q='+encodeURIComponent(term)+'&kind='+kind+'&page='+page)
  return <><div className="page-heading"><div><h1>Evidence library</h1><p>Original records, observed dates, and source provenance.</p></div><span>{r.data?.total.toLocaleString()||'…'} records</span></div><form className="library-search" onSubmit={e=>{e.preventDefault();setTerm(query);setPage(1)}}><label className="search-field"><Search size={18}/><input aria-label="Search evidence" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search a CVE, technique, actor or product"/></label><select aria-label="Record type" value={kind} onChange={e=>{setKind(e.target.value);setPage(1)}}><option value="">All record types</option>{['vulnerability','technique','group','software','mitigation','guidance'].map(k=><option key={k}>{k}</option>)}</select><button>Search</button></form>{r.error&&<p className="error">{r.error}</p>}<div className="library-layout"><div><div className="record-list">{r.data?.items.map(item=><button className={selected?.id===item.id?'selected':''} key={item.id} onClick={()=>setSelected(item)}><span>{item.title}</span><small>{item.source} · {item.kind}</small><ChevronRight size={17}/></button>)}{r.data&&r.data.items.length===0&&<p>No records match this search. Try another term or type.</p>}{!r.data&&!r.error&&<p>Loading evidence…</p>}</div><div className="pagination"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page}</span><button disabled={!r.data||page*30>=r.data.total} onClick={()=>setPage(p=>p+1)}>Next</button></div></div><aside className="record-detail">{selected?<><h2>{selected.title}</h2><SourceLink url={selected.url}>{selected.source}</SourceLink><small>Observed {date(selected.fetched_at)}</small><p>{selected.text}</p><details><summary>Structured fields</summary><pre>{JSON.stringify(selected.facts,null,2)}</pre></details><details><summary>SHA-256 provenance</summary><code>{selected.sha256}</code></details></>:<><BookOpen size={28}/><h2>Inspect a record</h2><p>Select a source record to read its original text and structured fields.</p></>}</aside></div></>
}

function Cases({review,onOpen}:{review:boolean;onOpen:(inv:Investigation)=>void}) {
  const r=useData<Investigation[]>(review?'/reviews':'/history'),[selected,setSelected]=useState<Investigation|null>(null),[note,setNote]=useState(''),[message,setMessage]=useState('')
  async function decide(status:string){if(!selected)return;try{await request('/investigations/'+selected.id+'/review',{status,note});setMessage('Review saved. Original evidence status is unchanged.');r.reload();setSelected({...selected,review_status:status,review_note:note})}catch(e){setMessage((e as Error).message)}}
  return <><div className="page-heading"><div><h1>{review?'Review queue':'Investigation history'}</h1><p>{review?'Make uncertainty a recorded decision.':'Your questions, findings, and exact evidence trail.'}</p></div><button onClick={r.reload}><RefreshCw size={15}/>Refresh</button></div>{r.error&&<p className="error">{r.error}</p>}<div className="table-scroll"><table><thead><tr><th>Question</th><th>Owner / observed</th><th>Answer status</th><th>Review</th><th>Action</th></tr></thead><tbody>{r.data?.map(inv=><tr key={inv.id}><td>{inv.question}</td><td>{inv.owner}<small>{date(inv.created_at)}</small></td><td><Status value={inv.status}/></td><td>{inv.review_status}</td><td><button onClick={()=>review?(setSelected(inv),setNote(inv.review_note),setMessage('')):onOpen(inv)}>Open <ArrowUpRight size={14}/></button></td></tr>)}</tbody></table></div>{r.data?.length===0&&<p className="empty">{review?'No cases are waiting in this review queue.':'Your investigations will appear here after your first question.'}</p>}{selected&&review&&<section className="review-case"><h2>Review decision</h2><label>Review note<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={4000}/></label><div className="case-actions"><button onClick={()=>decide('approved')}><Check size={16}/>Approve review</button><button onClick={()=>decide('rejected')}>Reject review</button><button onClick={()=>setSelected(null)}>Close case</button></div>{message&&<p role="status">{message}</p>}<ResultView inv={selected}/></section>}</>
}

function SourcePage({admin}:{admin:boolean}) {
  const r=useData<Sources>('/sources'),[busy,setBusy]=useState(''),[message,setMessage]=useState('')
  async function refresh(id:string){setBusy(id);setMessage('');try{await request('/sources/'+id+'/refresh',{});setMessage('Source refreshed and index rebuilt.');r.reload()}catch(e){setMessage((e as Error).message);r.reload()}finally{setBusy('')}}
  return <><div className="page-heading"><div><h1>Source operations</h1><p>Evidence freshness is a source property, not an assumption.</p></div></div>{r.error&&<p className="error">{r.error}</p>}{message&&<p className="notice" role="status">{message}</p>}<div className="source-operations">{r.data?.feeds.map(feed=><div key={feed.id}><h2>{feed.id.toUpperCase()}</h2><SourceLink url={feed.url}>Official feed</SourceLink>{admin&&<button disabled={!!busy} onClick={()=>refresh(feed.id)}><RefreshCw size={15}/>{busy===feed.id?'Refreshing…':'Refresh source'}</button>}</div>)}</div><h2>Ingestion log</h2><div className="table-scroll"><table><thead><tr><th>Source</th><th>Observed</th><th>Status</th><th>Records</th><th>Details</th></tr></thead><tbody>{r.data?.runs.map(run=><tr key={run.id}><td>{run.source}</td><td>{date(run.created_at)}</td><td><Status value={run.status}/></td><td>{run.count}</td><td>{run.error||'—'}</td></tr>)}</tbody></table></div><p className="notice">NVD and CVE Program records are fetched for named CVEs. OWASP is a pinned 2021 edition. The corpus is not a complete mirror of every CVE.</p></>
}

function Team({profile}:{profile:Profile}) {
  const settings=useData<Settings>('/settings'),users=useData<TeamUser[]>(profile.role==='admin'?'/admin/users':'/auth/me'),audit=useData<AuditEvent[]>(profile.role==='admin'?'/admin/audit':'/health')
  const [name,setName]=useState(''),[password,setPassword]=useState(''),[role,setRole]=useState('analyst'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
  async function add(e:FormEvent){e.preventDefault();setBusy(true);try{await request('/admin/users',{username:name,password,role});setName('');setPassword('');setMessage('Account created.');users.reload();audit.reload()}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
  async function disable(id:string){try{await request('/admin/users/'+id+'/disable',{});users.reload();audit.reload();setMessage('Account disabled; its sessions can no longer access the workspace.')}catch(e){setMessage((e as Error).message)}}
  return <><div className="page-heading"><div><h1>Team settings</h1><p>Shared access. Server-managed providers. Visible operational limits.</p></div></div><h2>Deployment</h2><p>{settings.data?.deployment} · {settings.data?.retrieval_mode} retrieval · {settings.data?.history_retention_days} day ordinary history retention.</p>{settings.data?.dense_error&&<p className="notice">{settings.data.dense_error}</p>}<h2>Optional AI providers</h2><div className="table-scroll"><table><thead><tr><th>Provider</th><th>Model</th><th>Available</th><th>Processing</th></tr></thead><tbody>{settings.data?.providers.map(p=><tr key={p.id}><td>{p.id}</td><td>{p.model||'Not configured'}</td><td>{p.configured?'Configured':'Unavailable'}</td><td>{p.external?'External, consent required':'Team server'}</td></tr>)}</tbody></table></div><p className="notice">Evidence-only mode works without any AI provider. Administrators configure keys and model IDs in the server environment, then restart. Keys never reach this browser.</p>{profile.role==='admin'&&<><h2>Team accounts</h2><form className="account-form" onSubmit={add}><label>Username<input value={name} onChange={e=>setName(e.target.value)} required maxLength={80}/></label><label>Initial password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={12} required autoComplete="new-password"/></label><label>Role<select value={role} onChange={e=>setRole(e.target.value)}><option>analyst</option><option>reviewer</option><option>admin</option></select></label><button disabled={busy}>{busy?'Creating…':'Create account'}</button></form>{message&&<p role="status">{message}</p>}<div className="table-scroll"><table><thead><tr><th>Username</th><th>Role</th><th>Status</th><th>Action</th></tr></thead><tbody>{Array.isArray(users.data)&&users.data.map(u=><tr key={u.id}><td>{u.username}</td><td>{u.role}</td><td>{u.active?'Active':'Disabled'}</td><td>{u.active&&u.username!==profile.username&&<button onClick={()=>disable(u.id)}>Disable account</button>}</td></tr>)}</tbody></table></div><h2>Audit trail</h2><div className="table-scroll"><table><thead><tr><th>Observed</th><th>Actor</th><th>Action</th><th>Details</th></tr></thead><tbody>{Array.isArray(audit.data)&&audit.data.map((a,i)=><tr key={i}><td>{date(a.created_at)}</td><td>{a.actor}</td><td>{a.action}</td><td><code>{JSON.stringify(a.detail)}</code></td></tr>)}</tbody></table></div></>}</>
}

function AnalystApp({profile,onLogout}:{profile:Profile;onLogout:()=>void}) {
  const [route,setRoute]=useState('workspace'),[openInv,setOpenInv]=useState<Investigation|null>(null),[mobile,setMobile]=useState(false)
  const overview=useData<Overview>('/overview')
  const nav=[['workspace','Workspace',Search],['library','Evidence library',BookOpen],...(profile.role!=='analyst'?[['reviews','Review queue',ShieldCheck]]:[]),['history','History',History],['sources','Sources',Database],['team','Team settings',Settings2]] as const
  function navigate(id:string){setRoute(id);setMobile(false);overview.reload();if(id==='workspace')setOpenInv(null)}
  return <div className="app-shell"><aside className={'app-sidebar '+(mobile?'mobile-open':'')}><div className="wordmark"><img src="/mark.svg" alt=""/>ThreatLeans</div><button className="close-nav" aria-label="Close navigation" onClick={()=>setMobile(false)}><X/></button><nav aria-label="Workspace">{nav.map(([id,label,Icon])=><button key={id as string} className={route===id?'active':''} onClick={()=>navigate(id as string)}><Icon size={18}/><span>{label as string}</span>{id==='reviews'&&!!overview.data?.pending_reviews&&<small>{overview.data.pending_reviews}</small>}</button>)}</nav><div className="sidebar-foot"><span>Source-bound intelligence.</span><small>Optional AI. Always evidence.</small><button onClick={onLogout}><LogOut size={16}/>Sign out</button></div></aside><div className="app-body"><header className="app-top"><button className="mobile-toggle" aria-label="Open navigation" onClick={()=>setMobile(true)}><Menu size={20}/></button><span>ThreatLeans SOC <ChevronRight size={14}/> {route==='workspace'?'Investigation':route}</span><div><span className="user-avatar">{profile.username.slice(0,2).toUpperCase()}</span>{profile.username}<small>{profile.role}</small></div></header><main className="app-content">{route==='workspace'&&<Workspace overview={overview.data} openInv={openInv}/>} {route==='library'&&<Library/>}{route==='history'&&<Cases review={false} onOpen={inv=>{setOpenInv(inv);setRoute('workspace')}}/>}{route==='reviews'&&<Cases review onOpen={()=>{}}/>}{route==='sources'&&<SourcePage admin={profile.role==='admin'}/>} {route==='team'&&<Team profile={profile}/>}</main></div></div>
}

export default function App() {
  const [profile,setProfile]=useState<Profile|null>(null),[checking,setChecking]=useState(true),[signin,setSignin]=useState(false)
  useEffect(()=>{request<Profile>('/auth/me').then(p=>{setCsrf(p.csrf);setProfile(p)}).catch(()=>{}).finally(()=>setChecking(false))},[])
  async function logout(){try{await request('/auth/logout',{})}finally{setCsrf('');setProfile(null);setSignin(false)}}
  if(checking)return <div className="boot" role="status">Opening ThreatLeans…</div>
  if(profile)return <AnalystApp profile={profile} onLogout={logout}/>
  return signin?<SignIn onLogin={setProfile} onBack={()=>setSignin(false)}/>:<Landing onEnter={()=>setSignin(true)}/>
}
